services:
    file_system:
      class: \Symfony\Component\Filesystem\Filesystem
    category_factory:
      class: \Multidoc\Factories\CategoryFactory
    project_factory:
      class: \Multidoc\Factories\ProjectFactory
      arguments: []
    route_factory:
      class: \Multidoc\Factories\RouteFactory
      arguments: []
    abstract_factory:
      class: \Multidoc\Factories\AbstractFactory
      arguments: ['@project_factory', '@route_factory', '@category_factory']
    environment_renderer:
      class: \Multidoc\Renderers\EnvironmentRenderer
    category_renderer:
      class: \Multidoc\Renderers\CategoryRenderer
      arguments: []
    file_content_parser_service:
      class: \Multidoc\Services\FileContentParserService
      arguments: ['@abstract_factory','@data_normalizer']
    input_file_service:
      class: \Multidoc\Services\InputFileService
    data_normalizer:
      class: \Multidoc\Services\DataNormalizerService
    output_file_service:
      class: \Multidoc\Services\OutputFileService
      arguments: ['@file_system','@category_renderer']
    multidoc_service:
      class: \Multidoc\Services\MultidocService
      arguments: ['@input_file_service', '@file_content_parser_service','@output_file_service']