services:
  file_system:
    class: \Symfony\Component\Filesystem\Filesystem
  category_normalizer:
    class: \MultidocParser\Normalizers\CategoryNormalizer
  data_normalizer:
    class: \MultidocParser\Normalizers\DataNormalizer
  environment_renderer:
    class: \MultidocParser\Renderers\EnvironmentRenderer
  category_renderer:
    class: \MultidocParser\Renderers\CategoryRenderer
  validation_service:
    class: \MultidocParser\Services\ValidationService
  file_content_parser_service:
    class: \MultidocParser\Services\FileContentParserService
    arguments: [ '@validation_service','@data_normalizer', '@category_normalizer' ]
  input_file_service:
    class: \MultidocParser\Services\InputFileService
  output_file_service:
    class: \MultidocParser\Services\OutputFileService
    arguments: [ '@file_system','@category_renderer' ]
  multidoc_parser_service:
    class: \MultidocParser\Services\MultidocParserService
    arguments: [ '@input_file_service', '@file_content_parser_service','@output_file_service' ]