parameters:
    mailer.transport: sendmail

services:
    file_system:
      class: \Symfony\Component\Filesystem\Filesystem

    status_factory:
      class: \Multidoc\Factories\StatusFactory
    tag_factory:
      class: \Multidoc\Factories\TagFactory
    parameter_factory:
      class: \Multidoc\Factories\ParameterFactory
    category_factory:
      class: \Multidoc\Factories\CategoryFactory
    environment_factory:
      class: \Multidoc\Factories\EnvironmentFactory
    header_factory:
      class: \Multidoc\Factories\HeaderFactory
    request_factory:
      class: \Multidoc\Factories\RequestFactory
      arguments: ['@header_factory','@parameter_factory']
    response_factory:
      class: \Multidoc\Factories\ResponseFactory
      arguments: ['@header_factory']
    project_factory:
      class: \Multidoc\Factories\ProjectFactory
      arguments: ['@environment_factory']
    route_factory:
      class: \Multidoc\Factories\RouteFactory
      arguments: ['@request_factory','@response_factory', '@status_factory', '@tag_factory']
    abstract_factory:
      class: \Multidoc\Factories\AbstractFactory
      arguments: ['@project_factory', '@route_factory', '@category_factory']

    environment_renderer:
      class: \Multidoc\Renderers\EnvironmentRenderer
    project_renderer:
      class: \Multidoc\Renderers\ProjectRenderer
      arguments: ['@environment_renderer']
    parameter_renderer:
      class: \Multidoc\Renderers\ParameterRenderer
    status_renderer:
      class: \Multidoc\Renderers\StatusRenderer
    tag_renderer:
      class: \Multidoc\Renderers\TagRenderer
    header_renderer:
      class: \Multidoc\Renderers\HeaderRenderer
    request_renderer:
      class: \Multidoc\Renderers\RequestRenderer
      arguments: ['@header_renderer','@parameter_renderer']
    response_renderer:
      class: \Multidoc\Renderers\ResponseRenderer
      arguments: ['@header_renderer']
    route_renderer:
      class: \Multidoc\Renderers\RouteRenderer
      arguments: ['@request_renderer','@response_renderer', '@status_renderer', '@tag_renderer']
    category_renderer:
      class: \Multidoc\Renderers\CategoryRenderer
      arguments: ['@route_renderer']

    file_content_parser_service:
      class: \Multidoc\Services\FileContentParserService
      arguments: ['@abstract_factory']
    input_file_service:
      class: \Multidoc\Services\InputFileService
    output_file_service:
      class: \Multidoc\Services\OutputFileService
      arguments: ['@file_system', '@project_renderer','@category_renderer']
    multidoc_service:
      class: \Multidoc\Services\MultidocService
      arguments: ['@input_file_service', '@file_content_parser_service','@output_file_service']